version: '3.5'
services:
  app:
    image: golang:1.13.1
    volumes:
      - .:/go/src/github.com/juve534/simple-chat
    working_dir: /go/src/github.com/juve534/simple-chat
    ports:
      - 80:8080
    depends_on:
      - redis
    networks:
      - app_net
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_net
networks:
  app_net:
    driver: bridge